# Spenden / Funding Sources
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [lukisch]
custom: ["https://um-bruch.org/"]
